# deployment_and_service.yaml

# Deployment YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-quote-app
spec:
  replicas: 3  # Number of replicas you want to run (you can adjust this as needed)
  selector:
    matchLabels:
      app: random-quote-app
  template:
    metadata:
      labels:
        app: random-quote-app
    spec:
      containers:
        - name: random-quote-app
          image: mydadisalive/quote-app:latest  # Correct image reference
          ports:
            - containerPort: 5000

---
# Service YAML
apiVersion: v1
kind: Service
metadata:
  name: random-quote-app-service
spec:
  selector:
    app: random-quote-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # Change to "ClusterIP" if you're using a local Kubernetes cluster
